apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack.fullname" . }}-backend
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
