apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack.fullname" . }}-frontend-nginx
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-nginx
spec:
  # must use index as value fields w/ hyphen because dot notation (e.g., .Values.my-value) will cause syntax error 
  type: {{ index .Values "frontend-nginx" "service" "type" }}
  ports:
    - port: {{ index .Values "frontend-nginx" "service" "port" }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-nginx
