apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fullstack.fullname" . }}-postgres
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  podSelector:
    matchLabels:
      {{- include "fullstack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  policyTypes:
    - Ingress
    - Egress
  # Ingress: Only allow from backend pods and kubelet health checks
  ingress:
    # Allow database connections from backend pods only
    - from:
        - podSelector:
            matchLabels:
              {{- include "fullstack.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}
    # Allow health checks from kubelet (node IPs - common private CIDRs)
    - from:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 172.16.0.0/12
        - ipBlock:
            cidr: 192.168.0.0/16
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}
  # Egress: Allow DNS and kubelet responses
  egress:
    # Allow DNS resolution (kube-dns/coredns in kube-system)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow health check responses to kubelet (node IPs)
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 172.16.0.0/12
        - ipBlock:
            cidr: 192.168.0.0/16
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}
    # Allow general cluster communication (optional, for backups, etc.)
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 172.16.0.0/12
        - ipBlock:
            cidr: 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
